faqs = {

    "What is your name?": "I am a helpful chatbot created to answer your questions.",
    "Who are you?": "I am an AI-based chatbot designed to help users.",
    "How are you?": "I am doing great! How can I help you today?",
    "What can you do?": "I can answer questions and provide helpful information.",
    "What time is it?": "I cannot tell real-time, but you can check your device clock.",
    "What day is today?": "Please check your calendar for today’s date.",
    "Good morning": "Good morning! Have a great day ahead.",
    "Good afternoon": "Good afternoon! Hope your day is going well.",
    "Good evening": "Good evening! How can I help you?",
    "Good night": "Good night! Sleep well.",
    "Hello": "Hello! How can I help you?",
    "Hi": "Hi there! What can I do for you?",
    "Thank you": "You’re welcome! Happy to help.",
    "Thanks": "Anytime! 😊",
    "Sorry": "No problem at all!",
    "How old are you?": "I don’t have an age like humans.",
    "Where are you from?": "I exist digitally, not in a physical location.",
    "Can you help me?": "Yes, I will try my best to help you.",
    "What is your purpose?": "My purpose is to assist and answer questions.",
    "Do you sleep?": "No, I am always available.",
    "Do you eat?": "No, I don’t need food.",
    "Are you human?": "No, I am an AI chatbot.",
    "Can you learn?": "I improve through training, not like humans.",
    "What is your favorite color?": "I don’t have personal preferences.",
    "Tell me a joke": "Why don’t programmers like nature? Too many bugs!",
    "Are you smart?": "I try to be helpful and informative.",
    "Can you talk?": "I communicate using text.",
    "Can you think?": "I process information, but I don’t think like humans.",
    "What is life?": "Life is a journey of growth and learning.",
    "What is happiness?": "Happiness is feeling content and satisfied.",
    "How to stay healthy?": "Eat well, exercise, and rest properly.",
    "What is stress?": "Stress is mental or emotional pressure.",
    "How to reduce stress?": "Relax, exercise, and take breaks.",
    "What is success?": "Success means achieving your goals.",
    "What is failure?": "Failure is an opportunity to learn.",
    "What is friendship?": "Friendship is a bond of trust and care.",
    "What is love?": "Love is deep affection and care.",
    "What is time management?": "Managing time efficiently to complete tasks.",
    "How to be confident?": "Believe in yourself and practice regularly.",
    "What is discipline?": "Discipline means self-control and consistency.",
    "How to focus on studies?": "Avoid distractions and make a study plan.",
    "What is motivation?": "Motivation is the drive to achieve goals.",
    "How to stay motivated?": "Set clear goals and reward progress.",
    "What is patience?": "Patience means staying calm while waiting.",
    "What is honesty?": "Honesty means telling the truth.",
    "What is kindness?": "Kindness is helping others with care.",
    "Who made you?": "I was created by developers as a learning project.",
    "What is AI?": "Artificial Intelligence is the simulation of human intelligence in machines.",
    "What is Machine Learning?": "Machine Learning is a subset of AI that allows systems to learn from data.",
    "What is Deep Learning?": "Deep Learning is a subset of Machine Learning using neural networks.",
    "What is Python?": "Python is a high-level, interpreted programming language.",
    "Why is Python popular?": "Python is popular because it is simple, readable, and powerful.",
    "What is NLP?": "Natural Language Processing helps machines understand human language.",
    "What is a chatbot?": "A chatbot is a program that can interact with users using text or voice.",
    "What is an FAQ chatbot?": "An FAQ chatbot answers predefined frequently asked questions.",
    "How does this chatbot work?": "It matches user questions with stored FAQs using similarity.",
    "What is cosine similarity?": "Cosine similarity measures how similar two texts are.",
    "What is TF-IDF?": "TF-IDF converts text into numerical vectors for comparison.",
    "What is Flask?": "Flask is a lightweight Python web framework.",
    "Why use Flask?": "Flask is simple and easy for beginners to build web apps.",
    "What is a web server?": "A web server handles requests from browsers.",
    "What is localhost?": "Localhost refers to your own computer.",
    "What is port 5000?": "Port 5000 is the default port used by Flask.",
    "What is HTML?": "HTML is used to create the structure of web pages.",
    "What is CSS?": "CSS is used to style and design web pages.",
    "What is JavaScript?": "JavaScript adds interactivity to web pages.",
    "What is backend development?": "Backend development handles server-side logic.",
    "What is frontend development?": "Frontend development handles user interfaces.",
    "What is full stack development?": "Full stack development includes frontend and backend.",
    "What is data science?": "Data science involves extracting insights from data.",
    "What is big data?": "Big data refers to extremely large datasets.",
    "What is cloud computing?": "Cloud computing provides computing resources over the internet.",
    "What is cybersecurity?": "Cybersecurity protects systems from digital attacks.",
    "What is encryption?": "Encryption converts data into secure code.",
    "What is a database?": "A database stores and manages data.",
    "What is SQL?": "SQL is used to manage relational databases.",
    "What is API?": "API allows software applications to communicate.",
    "What is REST API?": "REST API follows standard rules for web communication.",
    "What is JSON?": "JSON is a lightweight data format.",
    "What is Git?": "Git is a version control system.",
    "What is GitHub?": "GitHub hosts Git repositories online.",
    "What is DevOps?": "DevOps combines development and operations.",
    "What is Docker?": "Docker is a containerization platform.",
    "What is virtualization?": "Virtualization creates virtual systems.",
    "What is operating system?": "An operating system manages computer hardware.",
    "What is Windows?": "Windows is an operating system by Microsoft.",
    "What is Linux?": "Linux is an open-source operating system.",
    "What is open source?": "Open source software is freely available.",
    "What is software testing?": "Software testing checks for bugs.",
    "What is debugging?": "Debugging removes errors from code.",
    "What is compiler?": "A compiler converts code into machine language.",
    "What is interpreter?": "An interpreter runs code line by line.",
    "What is algorithm?": "An algorithm is a step-by-step solution.",
    "What is data structure?": "Data structures organize data efficiently.",
    "What is array?": "An array stores multiple values.",
    "Who developed this chatbot?": "This chatbot was developed as an academic project."

}
